log:
  colorSwitch: true
  level: 4
socks:
  host: 0.0.0.0:1080
  threads: 0
  timeout:
    switch: false
    client: 60s
    target: 60s
  bound: false
  mitmSwitch: true
  dump:
    switch: false
    port: 8000
tls:
  mitmSwitch: true
  verifyFinished: false
  verifyMAC: false
  defaultSNI: okii.com
http:
  mitmSwitch: true
  proxy: http://127.0.0.1:8080
dns: 114.114.114.114
ca:
  domain: www.digicert.com
  cert: config/ca/ca.crt
  key: config/ca/ca.key
db:
  ram:
    logSwitch: false
  disk:
    logSwitch: false
    path: config/sqlite/main.db